spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/db_test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 1000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
logging:
  level:
    com:
      jd:
        jdemo:
          mapper: debug