spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/db_test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      #max-idle: 10 已经不推荐使用
      max-wait: 1000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
jd:
  resources:
    jim:
      url: jim://2581594387536019499/80000013
logging:
  level:
    com:
      jd:
        jdemo:
          mapper: debug
### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://localhost:8080/
    ### xxl-job executor address
    executor:
      appname: jdemo
      ip:
      port: 9999
      ### xxl-job log path
      logpath: c://data/applogs/xxl-job/jobhandler
      ### xxl-job log retention days
      logretentiondays: 30
    ### xxl-job, access token
    accessToken: